version: '3'
      
services:
  dc-gogs:
    image: gogs/gogs
    container_name: dc-gogs
    volumes:
      - ./gogs:/data
    ports:
      - "3000:3000"
    restart: always
          
  dc-drone-server:
    image: drone/drone:1.2
    container_name: dc-drone-server
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./drone:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - DRONE_USER_CREATE=username:carello,admin:true
      - DRONE_OPEN=true
      - DRONE_ORGS=chet
      - DRONE_RUNNER_NETWORKS=${CI_NET}
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_GOGS=true
      - DRONE_GOGS_SERVER=${DRONE_GOGS_SERVER}
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_TLS_AUTOCERT=false
      - DRONE_LOGS_DEBUG=true
      - DRONE_LOGS_PRETTY=true
#      - DRONE_SYSTEM_HOST=${HOSTIP}
