---
pipeline:
  test:
    image: carello/pythonbase:latest
    commands:
      - cp -r . /app
      - cd /app
      - pip install -r requirements.txt
      - python tests.py
    
  docker:
    secrets: [ docker_username, docker_password ]
    image: plugins/docker
    dockerfile: Dockerfile
    action: build
    tags: latest
    repo: carello/cicd-app
    registry: docker.io
              
  deploy:   
    image: sh4d1/drone-kubernetes
    kubernetes_template: deployment-app.yaml
    kubernetes_namespace: default
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
