apiVersion: v1
kind: Service
metadata:
  name: cicd-app
  labels:
    app: cicd-app
spec:
  ports:
    - port: 5010
      targetPort: 5010
  selector:
    app: cicd-app
    tier: cicd-app
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cicd-app
  labels:
    app: cicd-app
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cicd-app
        tier: cicd-app
    spec:
      containers:
      - image: carello/cicd-app:latest
        name: cicd-app
        ports:
        - containerPort: 5010
          name: cicd-app
